import SwiftUI

struct ContentView: View {
    var body: some View {
        VStack {
            Image("me")
                .resizable()
                .aspectRatio(contentMode: .fit)
                .frame(width: 300, height:300)
                .offset(x: 20, y:300)
                
            .frame(minWidth: /*@START_MENU_TOKEN@*/0/*@END_MENU_TOKEN@*/, idealWidth: /*@START_MENU_TOKEN@*/100/*@END_MENU_TOKEN@*/, maxWidth: /*@START_MENU_TOKEN@*/.infinity/*@END_MENU_TOKEN@*/, minHeight: /*@START_MENU_TOKEN@*/0/*@END_MENU_TOKEN@*/, idealHeight: /*@START_MENU_TOKEN@*/100/*@END_MENU_TOKEN@*/, maxHeight: /*@START_MENU_TOKEN@*/.infinity/*@END_MENU_TOKEN@*/, alignment: /*@START_MENU_TOKEN@*/.center/*@END_MENU_TOKEN@*/)
            .background(LinearGradient(colors: [.white,.cyan, .pink,.cyan,.white,.cyan, .pink,Color.white,.cyan, .pink,Color.white,.cyan, .pink,Color.white,.cyan, .pink,.cyan], startPoint: .top, endPoint: .bottom))
                .ignoresSafeArea()
            
            Text("Kaitlyn")
                .font(.custom("Big Caslon",fixedSize:30))
                .foregroundColor(.orange)
                .offset(x:100, y:-120)
               .rotationEffect(.degrees(90))
            Text("Junior")
                .font(.custom("Cochin",fixedSize:30))
                .foregroundColor(.brown)
                .offset(x:-120, y: -10)
            Text("Fall+Winter")
                .font(.custom("Hoefler Text",fixedSize:30))
                .foregroundColor(.green)
                .offset(x:-130, y: 300)
            Image(systemName: "heart")
                .resizable()
                .foregroundColor(.pink)
                .aspectRatio(contentMode: .fit)
                .frame(width: 500, height:60)
                .offset(x:150,y:-100)
            Image(systemName: "leaf")
                .resizable()
                .foregroundColor(.green)
                .aspectRatio(contentMode: .fit)
                .frame(width: 50, height:50)
                .offset(x:-90,y:-500)
            Image(systemName: "tree")
                .resizable()
                .foregroundColor(.brown)
                .aspectRatio(contentMode: .fit)
                .frame(width: 50, height:50)
                .offset(x:-120,y:-150)
            Image(systemName: "globe.americas.fill")
                .resizable()
                .foregroundColor(/*@START_MENU_TOKEN@*/.blue/*@END_MENU_TOKEN@*/)
                .aspectRatio(contentMode: .fit)
                .frame(width: 50, height:50)
                .offset(x:-100,y:10)
            Image(systemName: "music.note")
                .resizable()
                .foregroundColor(.purple)
                .aspectRatio(contentMode: .fit)
                .frame(width: 50, height:50)
                .offset(x:140,y:-20)
            Image("peanut")
                .resizable()
                .aspectRatio(contentMode: .fit)
                .frame(width: 300, height:300)
                .offset(x: 20, y:-10)

        }
    }
}
